version: '3.9'
services:
  solar_forecaster:
    build: ./solar_forecaster
    container_name: solar_forecaster
    ports:
      - "8001:8000"
    volumes:
      - ./solar_forecaster:/app
    networks:
      renewable_net:
        aliases:
          - solar-forecaster

  grid_balancer:
    build: ./grid_balancer
    container_name: grid_balancer
    ports:
      - "8002:8000"
    depends_on:
      - solar_forecaster
    volumes:
      - ./grid_balancer:/app
    environment:
      - SOLAR_FORECASTER_URL=http://solar-forecaster:8000/forecast/
    networks:
      - renewable_net

networks:
  renewable_net:
    driver: bridge
